### ISSUE TITLE
Same results repeating twice - 8 total

### ISSUE THREAD

**Issue by ybird21** [fac-13/HyGiJeJe#25]
Hello code review buddies!

After searching a couple of times, I was given 8 results instead of four, and it was the same 4 films repeated. I'm not able to replicate this again, and can't find why it's happening, but I'll leave that window with 8 results open in case you want to inspect it.

**Comment by GiuliaTeggi** [comment]
Thanks! We aren't able to replicate this error, it looks fine to us :(
