### ISSUE TITLE
Commented out test code in DOM.js

### ISSUE THREAD

**Issue by caralemony** [fac-13/HyGiJeJe#31]
Well done with having the testDouble.js for testing!

However, it's always best practise to get rid of commented out code that you no longer need before merging too!

<img width="1105" alt="screen shot 2018-03-16 at 10 41 58" src="https://user-images.githubusercontent.com/26877512/37516656-bb25a75e-2906-11e8-87de-a69b89e51a5f.png">

**Comment by GiuliaTeggi** [comment]
Thank you, we deleted the text ;)
