### ISSUE TITLE
Console.log in logic.js - error message

### ISSUE THREAD

**Issue by caralemony** [fac-13/HyGiJeJe#37]
You have this line ```else {
        console.log("Status code" + xhr.status);
      }```

Instead of doing a console.log, this is the perfect place for you to instead put an error message in the page saying 'Sorry there is a problem with the movie database'. 

This way the user knows there is problem, instead of nothing happening.

**Comment by GiuliaTeggi** [comment]
Thank you, we've added an error message. ;)
